---
- name: "吊销证书"
  shell:
    cmd: '{{ item }}'
  args:
    chdir: /opt/ansible_work/EasyRSA-3.0.7
  loop:
  - './easyrsa revoke {{ client_user_name }}'
  - './easyrsa gen-crl'
  tags: ['never', 'revoke_client']

- name: "更新crl.pem"
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: "/etc/openvpn/cert"
    mode: "0600"
  loop:
  - "/opt/ansible_work/EasyRSA-3.0.7/pki/crl.pem"
  tags: ['never', 'revoke_client']
 
- name: "重命名客户端文件夹"
  shell:
    cmd: mv /etc/openvpn/client/{{ client_user_name }} /etc/openvpn/client/{{ client_user_name }}-revoke
  tags: ['never', 'revoke_client']

- name: "重启openvpn"
  systemd:
    name: openvpn
    state: restarted
  tags: ['never', 'revoke_client']
