---

- name: 添加公钥
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  loop:
  -  "{{ lookup('file', '/root/.ssh/AnsibleMaster.pub') }}"

- name: 禁用ssh密码登陆
  lineinfile:
    dest: /etc/ssh/sshd_config
    backrefs: yes
    regexp: "^PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    state: present

- name: 安装基础软件包
  yum:
    state: present
    name:
      - "at"
      - "gcc"
      - "gcc-c++"
      - "git"
      - "wget"
      - "curl"
      - "vim"
      - "mtr"
      - "tree"
      - "lsof"
      - "bind-utils"
      - "net-tools"
      - "epel-release"
      - "bash-completion"

- name: 创建.pip文件夹
  file:
    state: directory
    path: /root/.pip

- name: 安装pip源
  copy:
    src: pip.conf
    dest: /root/.pip

- name: 关闭selinux
  selinux:
    state: disabled

- name: 关闭firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name:
  lineinfile:
    path: /etc/vimrc
    regexp: r'{{ item }}'
    line: '{{ item }}'
    state: present
  loop:
  - 'set ts=4'
  - 'set expandtab'
  - 'set autoindent'

- name: "修改内核参数"
  sysctl:
    name: '{{ item.key_name }}'
    value: '{{ item.value_name }}'
    state: present
    reload: yes
  loop:
  - {'key_name': 'vm.swappiness', 'value_name': '0'}
  - {'key_name': 'kernel.sysrq', 'value_name': '1'}
  - {'key_name': 'net.ipv4.neigh.default.gc_stale_time', 'value_name': '120'}
  - {'key_name': 'net.ipv4.conf.all.rp_filter', 'value_name': '0'}
  - {'key_name': 'net.ipv4.conf.default.rp_filter', 'value_name': '0'}
  - {'key_name': 'net.ipv4.conf.default.arp_announce', 'value_name': '2'}
  - {'key_name': 'net.ipv4.conf.lo.arp_announce', 'value_name': '2'}
  - {'key_name': 'net.ipv4.conf.all.arp_announce', 'value_name': '2'}
  - {'key_name': 'net.ipv4.tcp_max_tw_buckets', 'value_name': '5000'}
  - {'key_name': 'net.ipv4.tcp_syncookies', 'value_name': '1'}
  - {'key_name': 'net.ipv4.tcp_max_syn_backlog', 'value_name': '1024'}
  - {'key_name': 'net.ipv4.tcp_synack_retries', 'value_name': '2'}

- name:
  lineinfile:
    path: /etc/security/limits.conf
    regexp: r'{{ item }}'
    line: '{{ item }}'
    state: present
  loop:
  - 'root soft nofile 65535'
  - 'root hard nofile 65535'
  - '* soft nofile 65535'
  - '* hard nofile 65535'

- name: 重启ssh服务器
  systemd:
    name: sshd
    state: restarted
